apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loadtest

resources:
  - namespace.yaml
  - priority-classes.yaml
  - service-accounts.yaml
  - configmaps.yaml
  - secrets.yaml
  - controller-deployment.yaml
  - admission-deployment.yaml
  - worker-deployment.yaml
  - frontend-deployment.yaml
  - mongodb-statefulset.yaml
  - redis-statefulset.yaml
  - ingress.yaml
  - grafana.yaml
  - monitoring.yaml
  - network-policies.yaml
  - pod-disruption-budgets.yaml
  - worker-hpa.yaml
  - vpa.yaml
