apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-sa
  namespace: loadtest
  labels:
    app: controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: loadtest
  labels:
    app: worker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: loadtest
  labels:
    app: frontend
