# ========== KEDA Autoscaling for Workers ==========
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaler
  namespace: loadtest
  labels:
    app: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  # Scale to 0 when no tests are running to save massive AWS costs (Spot instances)
  minReplicaCount: 0
  maxReplicaCount: 100
  pollingInterval: 5     # Check queue every 5 seconds
  cooldownPeriod:  300   # Wait 5 mins before scaling down
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
  - type: redis
    metadata:
      address: redis-service:6379
      listName: loadtest-task-queue
      listLength: "50" # 1 pod for every 50 pending load test tasks