apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: loadtest
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-gateway
  namespace: loadtest
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: loadtest
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: loadtest
spec:
  replicas: 1
